[package]
name = "robot_2"
version = "0.1.0"
edition = "2021"

[dependencies]
safe_drive = "0.4"
motor_lib = { git = "https://github.com/nityc-d-robo/motor_lib",branch =  "develop"}

[package.metadata.ros]
safe_drive_version = "0.4"
